// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJEMZlg14U3GwE0zBfvR8mSHwA7OCs84c',
    appId: '1:264954755740:web:bc1d200f1eabca8c5acb59',
    messagingSenderId: '264954755740',
    projectId: 'smartcalorieburner3',
    authDomain: 'smartcalorieburner3.firebaseapp.com',
    storageBucket: 'smartcalorieburner3.firebasestorage.app',
    measurementId: 'G-ZE0JFQVETB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSnMawSLLSZCH2RT1Sy__ERTOa0WzKd8U',
    appId: '1:264954755740:android:136a69afb1f8a9bb5acb59',
    messagingSenderId: '264954755740',
    projectId: 'smartcalorieburner3',
    storageBucket: 'smartcalorieburner3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8-5dDlTH36Pc0QaH8zQYocj3ZpEOYWlU',
    appId: '1:264954755740:ios:0c1321a37f2ff4085acb59',
    messagingSenderId: '264954755740',
    projectId: 'smartcalorieburner3',
    storageBucket: 'smartcalorieburner3.firebasestorage.app',
    iosBundleId: 'com.example.smartcalorieburnerfyp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8-5dDlTH36Pc0QaH8zQYocj3ZpEOYWlU',
    appId: '1:264954755740:ios:0c1321a37f2ff4085acb59',
    messagingSenderId: '264954755740',
    projectId: 'smartcalorieburner3',
    storageBucket: 'smartcalorieburner3.firebasestorage.app',
    iosBundleId: 'com.example.smartcalorieburnerfyp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJEMZlg14U3GwE0zBfvR8mSHwA7OCs84c',
    appId: '1:264954755740:web:d26b548a63612bcf5acb59',
    messagingSenderId: '264954755740',
    projectId: 'smartcalorieburner3',
    authDomain: 'smartcalorieburner3.firebaseapp.com',
    storageBucket: 'smartcalorieburner3.firebasestorage.app',
    measurementId: 'G-JHLCQHPBBV',
  );
}
